/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene.gltf -K -k 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="character_spot" position={[-0.07, 0.204, -0.696]} rotation={[-Math.PI, 0.439, -Math.PI]}>
          <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
            <primitive object={nodes.Hips} />
          </group>
          <group name="Wolf3D_Outfit_Top">
            <skinnedMesh name="Wolf3D_Outfit_Top001" geometry={nodes.Wolf3D_Outfit_Top001.geometry} material={materials['Wolf3D_Outfit_Top.001']} skeleton={nodes.Wolf3D_Outfit_Top001.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Top001_1" geometry={nodes.Wolf3D_Outfit_Top001_1.geometry} material={materials['Wolf3D_Teeth.001']} skeleton={nodes.Wolf3D_Outfit_Top001_1.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Top001_2" geometry={nodes.Wolf3D_Outfit_Top001_2.geometry} material={materials['Wolf3D_Eye.001']} skeleton={nodes.Wolf3D_Outfit_Top001_2.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Top001_3" geometry={nodes.Wolf3D_Outfit_Top001_3.geometry} material={materials['Wolf3D_Outfit_Bottom.001']} skeleton={nodes.Wolf3D_Outfit_Top001_3.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Top001_4" geometry={nodes.Wolf3D_Outfit_Top001_4.geometry} material={materials['Wolf3D_Body.001']} skeleton={nodes.Wolf3D_Outfit_Top001_4.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Top001_5" geometry={nodes.Wolf3D_Outfit_Top001_5.geometry} material={materials['Wolf3D_Skin.001']} skeleton={nodes.Wolf3D_Outfit_Top001_5.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Top001_6" geometry={nodes.Wolf3D_Outfit_Top001_6.geometry} material={materials['Wolf3D_Outfit_Footwear.001']} skeleton={nodes.Wolf3D_Outfit_Top001_6.skeleton} />
          </group>
        </group>
        <group name="Desk" position={[-0.074, 0, -1.521]}>
          <mesh name="Plane001_Plane002_BlackWood001" geometry={nodes.Plane001_Plane002_BlackWood001.geometry} material={materials['BlackWood.001']} />
          <mesh name="Plane001_Plane002_BlackWood001_1" geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry} material={materials['BlackCoatSteel.001']} />
          <mesh name="Plane001_Plane002_BlackWood001_2" geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry} material={materials['GrayPlastic.001']} />
          <mesh name="Plane001_Plane002_BlackWood001_3" geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry} material={materials['WhiteSteelScrew.001']} />
          <mesh name="Plane001_Plane002_BlackWood001_4" geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry} material={materials['BlackPlastic.001']} />
        </group>
        <group name="shelf" position={[-0.868, 1.694, -2.038]}>
          <mesh name="SM_ShelfSM_Shelf1_1" geometry={nodes.SM_ShelfSM_Shelf1_1.geometry} material={materials.lambert2SG} />
          <mesh name="SM_ShelfSM_Shelf1_1_1" geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={materials['lambert3SG.001']} />
        </group>
        <group name="LavaLamp" position={[-1.302, 2.071, -1.986]}>
          <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={materials.lambert4SG} />
          <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={materials['lambert2SG.001']} />
          <mesh name="Node-Mesh001_2" geometry={nodes['Node-Mesh001_2'].geometry} material={materials['lambert3SG.002']} />
        </group>
        <group name="keyboard" position={[0.042, 0.981, -1.346]} rotation={[0, 0.084, 0]} scale={0.611}>
          <mesh name="mesh425587018" geometry={nodes.mesh425587018.geometry} material={materials['mat21.004']} />
          <mesh name="mesh425587018_1" geometry={nodes.mesh425587018_1.geometry} material={materials['mat22.001']} />
          <mesh name="mesh425587018_2" geometry={nodes.mesh425587018_2.geometry} material={materials['mat9.002']} />
          <mesh name="mesh425587018_3" geometry={nodes.mesh425587018_3.geometry} material={materials['mat16.001']} />
        </group>
        <mesh name="mouse" geometry={nodes.mouse.geometry} material={materials['lambert3SG.003']} position={[-0.129, 0, -0.032]} />
        <group name="Plant" position={[-0.78, 1.071, -1.61]}>
          <mesh name="mesh2053840647" geometry={nodes.mesh2053840647.geometry} material={materials['mat9.003']} />
          <mesh name="mesh2053840647_1" geometry={nodes.mesh2053840647_1.geometry} material={materials['mat20.001']} />
          <mesh name="mesh2053840647_2" geometry={nodes.mesh2053840647_2.geometry} material={materials['mat21.005']} />
        </group>
        <group name="houseplant" position={[-2.019, -0.042, -1.526]}>
          <mesh name="Houseplant_7" geometry={nodes.Houseplant_7.geometry} material={materials['Black.001']} />
          <mesh name="Houseplant_7_1" geometry={nodes.Houseplant_7_1.geometry} material={materials['Brown.001']} />
          <mesh name="Houseplant_7_2" geometry={nodes.Houseplant_7_2.geometry} material={materials['Plant_Green.001']} />
        </group>
        <group name="Chair" position={[-0.156, 0, -0.683]} rotation={[0, -0.152, 0]}>
          <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials.Office_Cha} />
          <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials.Office_Cha_1} />
        </group>
        <mesh name="rug" geometry={nodes.rug.geometry} material={materials.phong1SG} position={[0, 0, 0.827]} />
        <group name="imac" position={[0.098, 0.956, -1.665]} rotation={[-Math.PI, 0.219, -Math.PI]}>
          <mesh name="IMac_01_Cube026-Mesh" geometry={nodes['IMac_01_Cube026-Mesh'].geometry} material={materials.FFFFFF} />
          <mesh name="IMac_01_Cube026-Mesh_1" geometry={nodes['IMac_01_Cube026-Mesh_1'].geometry} material={materials['1A1A1A']} />
        </group>
        <group name="ship" position={[-0.431, 2.022, -2.022]} rotation={[0, -1.405, 0]}>
          <mesh name="Lo_poly_Spaceship_03_by_Liz_Reddington_1" geometry={nodes.Lo_poly_Spaceship_03_by_Liz_Reddington_1.geometry} material={materials['lambert4SG.001']} />
          <mesh name="Lo_poly_Spaceship_03_by_Liz_Reddington_1_1" geometry={nodes.Lo_poly_Spaceship_03_by_Liz_Reddington_1_1.geometry} material={materials.lambert3SG} />
          <mesh name="Lo_poly_Spaceship_03_by_Liz_Reddington_1_2" geometry={nodes.Lo_poly_Spaceship_03_by_Liz_Reddington_1_2.geometry} material={materials['lambert2SG.002']} />
        </group>
        <group name="Plane">
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Floor} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.White} />
          <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials.Wall} />
          <mesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={materials.Glass} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
