/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene.gltf 
*/

import React, { useEffect } from "react";
import { useGLTF, useTexture, useVideoTexture } from '@react-three/drei';
import { motion } from "framer-motion-3d";
import * as THREE from "three";
import { animate, useMotionValue } from "framer-motion";
import { useFrame } from "@react-three/fiber";

export function Office(props) {

  const {section} = props;
  const { nodes, materials } = useGLTF('models/scene.gltf');
  const texture = useTexture("textures/baked.jpg");
  const textureVSCode = useVideoTexture("textures/vscode.mp4");

  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 1,
  });


  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.42,
  });

  const textureOpacity = useMotionValue(0);
  const glassTextureOpacity = useMotionValue(0);

  useEffect(() => {
    animate(textureOpacity, section === 0 ? 1 : 0, {
      duration: 0.8,
    });
    animate(glassTextureOpacity, section === 0 ? 0.42 : 0, {
      duration: 0.8,
    });
  }, [section]);

  useFrame(() => {
    textureMaterial.opacity = textureOpacity.get();
    textureGlassMaterial.opacity = glassTextureOpacity.get();
  });

  return (
    <group {...props} dispose={null}>
      <mesh 
      name="screen" 
      geometry={nodes.screen.geometry} 
      scale={[0.8, 1.45, 1.4]}
      position={[ 0.64, 1.3, -1.700]} 
      rotation={[Math.PI, 0.1, Math.PI / 2]} 
      >
        <meshBasicMaterial map={textureVSCode} toneMapped={false}/>
        </mesh>
      <motion.group 
      scale={[0, 0, 0]}
      animate={{
        scale: section === 0 ? 1 : 0,
      }}
      name="Desk" position={[-0.074, 0, -1.521]}>
          <mesh name="Plane001_Plane002_BlackWood001" geometry={nodes.Plane001_Plane002_BlackWood001.geometry} material={textureMaterial} />
          <mesh name="Plane001_Plane002_BlackWood001_1" geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry} material={textureMaterial} />
          <mesh name="Plane001_Plane002_BlackWood001_2" geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry} material={textureMaterial} />
          <mesh name="Plane001_Plane002_BlackWood001_3" geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry} material={textureMaterial} />
          <mesh name="Plane001_Plane002_BlackWood001_4" geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry} material={textureMaterial} />
        </motion.group>
        <group name="shelf" position={[-0.868, 1.694, -2.038]}>
          <mesh name="SM_ShelfSM_Shelf1_1" geometry={nodes.SM_ShelfSM_Shelf1_1.geometry} material={textureMaterial} />
          <mesh name="SM_ShelfSM_Shelf1_1_1" geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={textureMaterial} />
        </group>
        <motion.group 
      scale={[0, 0, 0]}
      animate={{
        scale: section === 0 ? 1 : 0,
      }}
       name="LavaLamp" position={[-1.302, 2.071, -1.986]}>
          <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={textureMaterial} />
          <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={textureMaterial} />
          <mesh name="Node-Mesh001_2" geometry={nodes['Node-Mesh001_2'].geometry} material={textureMaterial} />
        </motion.group>
        <group 
        name="keyboard" position={[0.042, 0.981, -1.346]} rotation={[0, 0.084, 0]} scale={0.611}>
          <mesh name="mesh425587018" geometry={nodes.mesh425587018.geometry} material={textureMaterial} />
          <mesh name="mesh425587018_1" geometry={nodes.mesh425587018_1.geometry} material={textureMaterial} />
          <mesh name="mesh425587018_2" geometry={nodes.mesh425587018_2.geometry} material={textureMaterial} />
          <mesh name="mesh425587018_3" geometry={nodes.mesh425587018_3.geometry} material={textureMaterial} />
        </group>
        <motion.mesh 
         scale={[0, 0, 0]}
         animate={{
           scale: section === 0 ? 1 : 0,
         }}
        name="mouse" geometry={nodes.mouse.geometry} material={textureMaterial} position={[-0.129, 0, -0.032]} />
        <group name="Plant" position={[-0.78, 1.071, -1.61]}>
          <mesh name="mesh2053840647" geometry={nodes.mesh2053840647.geometry} material={textureMaterial} />
          <mesh name="mesh2053840647_1" geometry={nodes.mesh2053840647_1.geometry} material={textureMaterial} />
          <mesh name="mesh2053840647_2" geometry={nodes.mesh2053840647_2.geometry} material={textureMaterial} />
        </group>
        <motion.group 
      scale={[0, 0, 0]}
      animate={{
        scale: section === 0 ? 1 : 0,
      }}
        name="houseplant" position={[-2.019, -0.042, -1.526]}>
          <mesh name="Houseplant_7" geometry={nodes.Houseplant_7.geometry} material={textureMaterial} />
          <mesh name="Houseplant_7_1" geometry={nodes.Houseplant_7_1.geometry} material={textureMaterial} />
          <mesh name="Houseplant_7_2" geometry={nodes.Houseplant_7_2.geometry} material={textureMaterial} />
        </motion.group>
        <motion.group 
      scale={[0, 0, 0]}
      animate={{
        scale: section === 0 ? 1 : 0,
      }} 
        
        name="Chair" position={[-0.156, 0, -0.683]} rotation={[0, -0.152, 0]}>
          <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={textureMaterial} />
          <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={textureMaterial} />
        </motion.group>
        <mesh name="rug" geometry={nodes.rug.geometry} material={textureMaterial} position={[0, 0, 0.827]} />
        <motion.group 
      scale={[0, 0, 0]}
      animate={{
        scale: section === 0 ? 1 : 0,
      }}
         name="imac" position={[0.098, 0.956, -1.665]} rotation={[-Math.PI, 0.219, -Math.PI]}>
          <mesh name="IMac_01_Cube026-Mesh" geometry={nodes['IMac_01_Cube026-Mesh'].geometry} material={textureMaterial} />
          {/* <mesh name="IMac_01_Cube026-Mesh_1" geometry={nodes['IMac_01_Cube026-Mesh_1'].geometry} material={textureMaterial} /> */}
        </motion.group>
         <motion.group 
         scale={[0, 0, 0]}
         animate={{
           scale: section === 0 ? 1 : 0,
         }}
        name="ship" position={[-0.431, 2.022, -2.022]} rotation={[0, -1.405, 0]}>
          <mesh name="Lo_poly_Spaceship_03_by_Liz_Reddington_1" geometry={nodes.Lo_poly_Spaceship_03_by_Liz_Reddington_1.geometry} material={textureMaterial} />
          <mesh name="Lo_poly_Spaceship_03_by_Liz_Reddington_1_1" geometry={nodes.Lo_poly_Spaceship_03_by_Liz_Reddington_1_1.geometry} material={textureMaterial} />
          <mesh name="Lo_poly_Spaceship_03_by_Liz_Reddington_1_2" geometry={nodes.Lo_poly_Spaceship_03_by_Liz_Reddington_1_2.geometry} material={textureMaterial} />
        </motion.group>
        <group name="Plane">
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={textureMaterial} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={textureMaterial} />
          <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={textureMaterial} />
          <mesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={textureGlassMaterial} />
        </group>
      </group>
  );
}

useGLTF.preload('models/scene.gltf');
useTexture.preload('textures/baked.jpg');
