/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene.gltf 
*/

import React from "react";
import { useGLTF, useTexture } from '@react-three/drei';

import * as THREE from "three";

export function Office(props) {
  const { nodes, materials } = useGLTF('models/scene.gltf');
  const texture = useTexture("textures/baked.jpg");
  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
  });


  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.42,
  });

  return (
    <group {...props} dispose={null}>
      <group name="Desk" position={[-0.074, 0, -1.521]}>
        <mesh name="Plane001_Plane002_BlackWood001" geometry={nodes.Plane001_Plane002_BlackWood001.geometry} material={textureMaterial} />
        <mesh name="Plane001_Plane002_BlackWood001_1" geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry} material={textureMaterial} />
        <mesh name="Plane001_Plane002_BlackWood001_2" geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry} material={textureMaterial} />
        <mesh name="Plane001_Plane002_BlackWood001_3" geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry} material={textureMaterial} />
        <mesh name="Plane001_Plane002_BlackWood001_4" geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry} material={textureMaterial} />
      </group>
      <group name="shelf" position={[-0.868, 1.694, -2.038]}>
        <mesh name="SM_ShelfSM_Shelf1_1" geometry={nodes.SM_ShelfSM_Shelf1_1.geometry} material={textureMaterial} />
        <mesh name="SM_ShelfSM_Shelf1_1_1" geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={textureMaterial} />
      </group>
      <group name="LavaLamp" position={[-1.302, 2.071, -1.986]}>
        <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh001_2" geometry={nodes['Node-Mesh001_2'].geometry} material={textureMaterial} />
      </group>
      <group name="keyboard" position={[-0.044, 0.981, -1.346]}>
        <mesh name="mesh425587018" geometry={nodes.mesh425587018.geometry} material={textureMaterial} />
        <mesh name="mesh425587018_1" geometry={nodes.mesh425587018_1.geometry} material={textureMaterial} />
        <mesh name="mesh425587018_2" geometry={nodes.mesh425587018_2.geometry} material={textureMaterial} />
        <mesh name="mesh425587018_3" geometry={nodes.mesh425587018_3.geometry} material={textureMaterial} />
      </group>
      <mesh name="mouse" geometry={nodes.mouse.geometry} material={textureMaterial} />
      <group name="Plant" position={[-0.78, 1.071, -1.61]}>
        <mesh name="mesh2053840647" geometry={nodes.mesh2053840647.geometry} material={textureMaterial} />
        <mesh name="mesh2053840647_1" geometry={nodes.mesh2053840647_1.geometry} material={textureMaterial} />
        <mesh name="mesh2053840647_2" geometry={nodes.mesh2053840647_2.geometry} material={textureMaterial} />
      </group>
      <group name="houseplant" position={[-2.019, -0.042, -1.526]}>
        <mesh name="Houseplant_7" geometry={nodes.Houseplant_7.geometry} material={textureMaterial} />
        <mesh name="Houseplant_7_1" geometry={nodes.Houseplant_7_1.geometry} material={textureMaterial} />
        <mesh name="Houseplant_7_2" geometry={nodes.Houseplant_7_2.geometry} material={textureMaterial} />
      </group>
      <mesh name="rug" geometry={nodes.rug.geometry} material={textureMaterial} position={[0, 0, 0.827]} />
      <group name="imac" position={[0.098, 0.956, -1.665]} rotation={[-Math.PI, 0.219, -Math.PI]}>
        <mesh name="IMac_01_Cube026-Mesh" geometry={nodes['IMac_01_Cube026-Mesh'].geometry} material={textureMaterial} />
        <mesh name="IMac_01_Cube026-Mesh_1" geometry={nodes['IMac_01_Cube026-Mesh_1'].geometry} material={textureMaterial} />
      </group>
      <group name="ship" position={[-0.431, 2.022, -2.022]} rotation={[0, -1.405, 0]}>
        <mesh name="Lo_poly_Spaceship_03_by_Liz_Reddington_1" geometry={nodes.Lo_poly_Spaceship_03_by_Liz_Reddington_1.geometry} material={textureMaterial} />
        <mesh name="Lo_poly_Spaceship_03_by_Liz_Reddington_1_1" geometry={nodes.Lo_poly_Spaceship_03_by_Liz_Reddington_1_1.geometry} material={textureMaterial} />
        <mesh name="Lo_poly_Spaceship_03_by_Liz_Reddington_1_2" geometry={nodes.Lo_poly_Spaceship_03_by_Liz_Reddington_1_2.geometry} material={textureMaterial} />
      </group>
      <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={textureMaterial} />
      <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={textureMaterial} />
      <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={textureMaterial} />
      <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={textureMaterial} />
      <mesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={textureGlassMaterial} />
    </group>
  );
}

useGLTF.preload('models/scene.gltf');
